HMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel.urls')),
    path('accounts/', include('allauth.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hotel/urls.py
from django.urls import path
from .views import RoomListView, BookingListView, BookingVIew, RoomDetailView, CancelBookingView
app_name='hotel'
urlpatterns = [
    path('room_list/', RoomListView, name='RoomListView'),
    path('booking_list/', BookingListView.as_view(), name='BookingListView'),
    path('booking_view/', BookingVIew.as_view(), name='booking_view'),
    path('room/<category>/', RoomDetailView.as_view(), name='RoomDetailView'),
    path('booking/cancel/<pk>/', CancelBookingView.as_view(), name='CancelBookingView'),
]

hotel/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy
# Create your models here.
class Room(models.Model):
    ROOM_CATEGORIES=(
        ('YAC','AC'),
        ('NAC','NON-AC'),
        ('DEL','DELUXE'),
        ('KIN','KING'),
        ('QUE','QUEEN'),
    )
    number=models.IntegerField()
    category=models.CharField(max_length=3, choices=ROOM_CATEGORIES)
    beds=models.IntegerField()
    capacity=models.IntegerField()
    def __str__(self):
        return f'{self.number} {self.category} with {self.beds} beds for {self.capacity} people'

class Booking(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room= models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in=models.DateTimeField()
    check_out=models.DateTimeField()
    def __str__(self):
        return f'{self.user} has booked {self.room} from {self.check_in} to {self.check_out}'
    def get_room_category(self):
        room_categories=dict(self.room.ROOM_CATEGORIES)
        room_Category=room_categories.get(self.room.category)
        return room_Category
    def get_cancel_booking_url(self):
        return reverse_lazy('hotel:CancelBookingView',args=[self.pk,])

hotel/forms.py
from django import forms
class AavailabilityForm(forms.Form):
    check_in=forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M",],  widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    check_out=forms.DateTimeField(required=True, input_formats=["%Y=%m-%dT%H:%M",],  widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))

hotel/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import ListView, FormView, View, DeleteView
from .models import Room, Booking
from .forms import AavailabilityForm
from django.urls import reverse, reverse_lazy
from hotel.booking_functions.availability import check_availability
from hotel.booking_functions.get_room_cat_url_list import get_room_cat_url_list
# Create your views here.
def RoomListView(request):
    room_cat_url_list=get_room_cat_url_list()
    context={
        'room_list':room_cat_url_list,
    }
    return render(request, 'room_list_view.html', context)
class BookingListView(ListView):
    model=Booking
    template_name='hotel/booking_list_view.html'
    def get_queryset(self,*args,**kwargs):
        if self.request.user.is_staff:
            booking_list=Booking.objects.all()
            return booking_list
        else:
            booking_list=Booking.objects.filter(user=self.request.user)
            return booking_list

class RoomDetailView(View):
    def get(self,request, *args,**kwargs):
        category=self.kwargs.get('category',None)
        room_list=Room.objects.filter(category=category)
        form=AavailabilityForm()
        if(len(room_list)>0):
            room=room_list[0]
            room_category=dict(room.ROOM_CATEGORIES).get(room.category, None)            
            context={
                'room_category' : room_category,
                'form':form,
            }
            return render(request, 'room_detail_view.html', context)
        else:
            return HttpResponse('Category does not exist')


    def post(self,request, *args,**kwargs):
        category=self.kwargs.get('category',None)
        room_list=Room.objects.filter(category=category)
        available_rooms=[]
        form=AavailabilityForm(request.POST)
        if form.is_valid():
            data=form.cleaned_data
        for room in room_list:
            if check_availability(room,data['check_in'], data['check_out']):
                available_rooms.append(room)
        if len(available_rooms)>0:
            room=available_rooms[0]
            booking = Booking.objects.create(
                user=self.request.user,
                room=room,
                check_in=data['check_in'],
                check_out=data['check_out']
            )
            booking.save()
            return HttpResponse(booking)
        else:
            return HttpResponse('All of this category of rooms are not available, kindly check for other rooms')

class BookingVIew(FormView):
    form_class= AavailabilityForm
    template_name='hotel/availability_form.html'

    def form_valid(self, form):
        data=form.cleaned_data
        room_list=Room.objects.filter(category=data['room_category'])
        available_rooms=[]
        for room in room_list:
            if check_availability(room,data['check_in'], data['check_out']):
                available_rooms.append(room)
        if len(available_rooms)>0:
            room=available_rooms[0]
            booking = Booking.objects.create(
                user=self.request.user,
                room=room,
                check_in=data['check_in'],
                check_out=data['check_out']
            )
            booking.save()
            return HttpResponse(booking)
        else:
            return HttpResponse('All of this category of rooms are not available, kindly check for other rooms')

class CancelBookingView(DeleteView):
    model=Booking
    template_name='hotel/booking_cancel_view.html'
    success_url=reverse_lazy('hotel:BookingListView')

templates/hotel/availability_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Availability form</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Book Room</button>
    </form>
    
</body>
</html>

templates/hotel/booking_cancel_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'hotel/css/room_detail_view.css' %}">

</head>

<body>

    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
        </div>

        <!-- Room Details -->
        <div class="room">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'hotel:RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="room-info">
                <h1>{{room_category}}</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}
                <h2>Are you sure you wanna cancel this Booking? Details-</h2>
                <h3>{{booking.room.number}}{{booking.get_room_category}} {{booking}}</h3>
                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit">Cancel the Booking</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>

templates/hotel/booking_list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking List</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'hotel/css/booking_list_view.css' %}">
</head>

<body>
    <div class="content">
        <div class="header">
            <div class="headings">
                <h1>Your Bookings</h1>
                <h2>Welcome dear {{user}}</h2>
            </div>
            <div class="home">
                <!-- Div 1: Back to Home -->
                <div class="home">
                    <a href="{% url 'hotel:RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
                </div>
            </div>

        </div>

        <div class="bookings">
            {% for booking in booking_list %}
            <div class="booking">
                <img src="https://images.unsplash.com/photo-1560067174-c5a3a8f37060?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80"
                    alt="">
                <div class="category">
                    <h2>{{booking.get_room_category}} Suite</h2>
                </div>
                <div class="from">
                    <h3>From: {{booking.check_in}}</h3>
                </div>
                <div class="to">
                    <h3>To: {{booking.check_out}}</h3>
                </div>
                <div class="beds">
                    <h3>Beds: {{booking.room.beds}}</h3>
                </div>
                <div class="capacity">
                    <h3>Capacity: {{booking.room.capacity}}</h3>
                </div>
                <div class="cancel"><a href="{{booking.get_cancel_booking_url}}" class="invisible"><i
                            class="far fa-2x fa-times-circle"> Cancel
                            Booking</i></a></div>

            </div>
            {% endfor %}
        </div>
</body>

</html>

templates/hotel/room_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RoomList</title>
</head>
<body>
    {% for room in room_list %}
        <h2>{{room}}</h2>
    {% endfor %}
</body>
</html>

templates/room_detail_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'hotel/css/room_detail_view.css' %}">

</head>

<body>

    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
        </div>

        <!-- Room Details -->
        <div class="room">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'hotel:RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="room-info">
                <h1>{{room_category}}</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_in">Check In : </label>
                    <input type="datetime-local" id="id_check_in" name="check_in">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_out">Check Out : </label>
                    <input type="datetime-local" id="id_check_out" name="check_out">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit">Book the Room</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>

templates/room_list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HotelMaa</title>
    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'hotel/css/room_list_view.css' %}">
</head>

<body>
    <!-- Brand -->
    <h1 id="brand">HotelMaa</h1>

    <!-- Main Content -->
    <div class="content">
        {% for room_category, room_url in room_list %}
        <div class="room">
            <a href="{{room_url}}">
                <img
                    src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">

                <h2>{{room_category}}</h2>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi</p>
            </a>
        </div>
        {% endfor %}

    </div>
</body>

</html>